var data = [
    {
        "No": "0",
        "Model": "Audi e-tron-sportback",
        "Rangeofcar": "Hybrid",
        "Brand": "AUDI",
        "Pricing": "69,100",
        "seller" : "best",
        "condition" : "new",
        "Description": "A kinetic design for an electric world.\nCoiled yet poised, the stylized potential of the e-tron Sportback is clear from any angle — it's designed to attract, electrify and generate envy of ownership.\nThoughtful composition leads to a positive recharge.\nPart sanctuary, part cockpit, the interior of the e-tron Sportback rewards the driver and the passengers with a combination of timeless refinement and next-gen technology.\n",
        "Details": "<tbody>\n    <tr>\n      <td>Condition:</td>\n      <td>New</td>\n      <td>Model:</td>\n      <td>e-tron-sportback</td>\n    </tr>\n    <tr>\n      <td>Price:</td>\n      <td>$69,100</td>\n      <td>Fuel:</td>\n      <td>electric</td>\n    </tr>\n    <tr>\n      <td>Body Style:</td>\n      <td>Hybrid</td>\n      <td>Doors:</td>\n      <td>5</td>\n    </tr>\n    <tr>\n      <td>Power:</td>\n      <td>402 hp/490 lb-ft</td>\n      <td>Make:</td>\n      <td>Audi</td>\n    </tr>\n    <tr>\n      <td>Year:</td>\n      <td>2021</td>\n      <td>Mileage:</td>\n      <td></td>\n    </tr>\n    <tr>\n      <td>Color:</td>\n      <td>Brilliant Black</td>\n      <td>Transmission:</td>\n      <td>Automatic</td>\n    </tr>\n    <tr>\n      <td>Battery:</td>\n      <td>95 kWh</td>\n    </tr>\n  </tbody>",
        "Image1": "../image/product/Audi e-tron-sportback/img1.jpg",
        "Image2": "../image/product/Audi e-tron-sportback/img2.jpg",
        "Image3": "../image/product/Audi e-tron-sportback/img3.jpg",
        "Image4": "../image/product/Audi e-tron-sportback/img4.jpg",
        "Image5": "../image/product/Audi e-tron-sportback/img5.jpg\n",
        "Image6": "../image/product/Audi e-tron-sportback/img6.jpg",
        "Image7": "./image/product/Audi e-tron-sportback/img1.jpg",
        "Image8": "./image/product/Audi e-tron-sportback/img2.jpg"
    },
    {
        "No": "1",
        "Model": "Audi A6",
        "Rangeofcar": "Sedan",
        "Brand": "AUDI",
        "Pricing": "54,900",
        "condition" : "new",
        "Description": "Never experience a case of mistaken identity.\nStarting from a new design direction first seen in the Audi Prologue concept car, the Audi A6 cuts a sharper profile with acute angles, defined edges and taut, muscular contours. Its lines take the eyes on a journey, while expressive surface language shapes its character.\nErgonomics takes the driver̕ s point of view.\nThey say location is everything. That's why the Audi MMI® touch response screens have been set at an angle that tilts towards the driver. The infotainment system is accessed through the upper screen, while controls for the heating, ventilation and seat settings appear on the lower screen.",
        "Details": "\n  <tbody>\n    <tr>\n      <td>Condition:</td>\n      <td>New</td>\n      <td>Model:</td>\n      <td>A6</td>\n    </tr>\n    <tr>\n      <td>Price:</td>\n      <td>$54.900</td>\n      <td>Fuel:</td>\n      <td>Premium</td>\n    </tr>\n    <tr>\n      <td>Body Style:</td>\n      <td>Sedan</td>\n      <td>Doors:</td>\n      <td>5</td>\n    </tr>\n    <tr>\n      <td>Power:</td>\n      <td>444 hp</td>\n      <td>Make:</td>\n      <td>Audi</td>\n    </tr>\n    <tr>\n      <td>Year:</td>\n      <td>2021</td>\n      <td>Mileage:</td>\n      <td>0-60 mhp 4.4 seconds</td>\n    </tr>\n    <tr>\n      <td>Torque:</td>\n      <td>369 lb-ft</td>\n      <td>Transmission:</td>\n      <td>Automatic</td>\n    </tr>\n    <tr>\n      <td>Engine:</td>\n      <td>2.9-liter six-cylinder</td>\n    </tr>\n  </tbody>\n\n\n",
        "Image1": "../image/product/Audi A6/img1.jpg",
        "Image2": "../image/product/Audi A6/img2.jpg",
        "Image3": "../image/product/Audi A6/img3.jpg",
        "Image4": "../image/product/Audi A6/img4.jpg",
        "Image5": "../image/product/Audi A6/img5.jpg",
        "Image6": "../image/product/Audi A6/img6.jpg",
        "Image7": "./image/product/Audi A6/img1.jpg",
        "Image8": "./image/product/Audi A6/img2.jpg"
    },
    {
        "No": "2",
        "Model": "Audi S6",
        "Rangeofcar": "Sedan",
        "Brand": "AUDI",
        "Pricing": "75,445",
        "status" : "hot",
        "condition" : "new",
        "Description": "Accelerating progress by design.\nA smooth curve that resists the wind. An acute angle to redirect to redirect airflow. The subtle upturn at the edge of a trunk lid helps create downforce. Design's purpose is as much functional as it is aesthetic.\nMinimalist design of a luxury space.\r\nThe uncluttered, smooth surfaces of MMI® touch response show this is design from a clean slate. The display screens are angled towards the driver to help optimize the view of the touchscreen icons.",
        "Details": "  <tbody>\r\n    <tr>\r\n      <td>Condition:</td>\r\n      <td>New</td>\r\n      <td>Model:</td>\r\n      <td>S6</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Price:</td>\r\n      <td>$75.445</td>\r\n      <td>Fuel:</td>\r\n      <td>Premium</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Body Style:</td>\r\n      <td>Sedan</td>\r\n      <td>Doors:</td>\r\n      <td>5</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Power:</td>\r\n      <td>444 hp</td>\r\n      <td>Make:</td>\r\n      <td>Audi</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Year:</td>\r\n      <td>2021</td>\r\n      <td>Mileage:</td>\r\n      <td>0-60 mhp 4.4 seconds</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Torque:</td>\r\n      <td>443 lb-ft</td>\r\n      <td>Transmission:</td>\r\n      <td>Automatic</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Engine:</td>\r\n      <td>2.9-liter six-cylinder</td>\r\n    </tr>\r\n  </tbody>\r\n",
        "Image1": "../image/product/Audi S6/img1.jpg",
        "Image2": "../image/product/Audi S6/img2.jpg",
        "Image3": "../image/product/Audi S6/img3.jpg",
        "Image4": "../image/product/Audi S6/img4.jpg",
        "Image5": "../image/product/Audi S6/img5.jpg",
        "Image6": "../image/product/Audi S6/img6.jpg",
        "Image7": "./image/product/Audi S6/img1.jpg",
        "Image8": "./image/product/Audi S6/img2.jpg"
    },
    {
        "No": "3",
        "Model": "Audi Q3",
        "Rangeofcar": "SUV",
        "Brand": "AUDI",
        "Pricing": "35,095",
        "condition" : "new",
        "Description": "Expectations were meant to be exceeded.\r\nWith standard quattro® all-wheel drive, bold exterior and interior design with thoughtful functionality, and many technology and connectivity features, the Q3 offers a strong entry to the Audi brand.\nA presence that’s larger than life.\r\nBoth inside and out, the Audi Q3 design exudes charisma and pushes boundaries. The fusion of the right-sized sport utility proportions and Audi identity is clear with every line, curve, and detail. With the Audi Q3, we didn’t hold anything back.",
        "Details": "  <tbody>\r\n    <tr>\r\n      <td>Condition:</td>\r\n      <td>New</td>\r\n      <td>Model:</td>\r\n      <td>Q3</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Price:</td>\r\n      <td>$35.095</td>\r\n      <td>Fuel:</td>\r\n      <td>Regular</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Body Style:</td>\r\n      <td>SUV</td>\r\n      <td>Doors:</td>\r\n      <td>5</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Power:</td>\r\n      <td>184 hp</td>\r\n      <td>Make:</td>\r\n      <td>Audi</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Year:</td>\r\n      <td>2021</td>\r\n      <td>Drivetrain:</td>\r\n      <td>quattro® all-wheel drive</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Torque:</td>\r\n      <td>258 lb-ft</td>\r\n      <td>Transmission:</td>\r\n      <td>Automatic</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Engine:</td>\r\n      <td>2.0-liter four-cylinder</td>\r\n    </tr>\r\n  </tbody>\r\n",
        "Image1": "../image/product/Audi Q3/img1.jpg",
        "Image2": "../image/product/Audi Q3/img2.jpg",
        "Image3": "../image/product/Audi Q3/img3.jpg",
        "Image4": "../image/product/Audi Q3/img4.jpg",
        "Image5": "../image/product/Audi Q3/img5.jpg",
        "Image6": "../image/product/Audi Q3/img6.jpg",
        "Image7": "./image/product/Audi Q3/img1.jpg",
        "Image8": "./image/product/Audi Q3/img2.jpg"
    },
    {
        "No": "4",
        "Model": "Toyota Camry LE hybrid 2021",
        "Rangeofcar": "Hybrid",
        "Brand": "Toyota",
        "Pricing": "27,270",
        "condition" : "new",
        "Description": "Hybrid Performance\r\nCamry Hybrid unites style and performance, all with added hybrid efficiency.\nAvailable All-Wheel Drive\r\nAll-Wheel Drive (AWD) performance gives you the confidence to venture further, no matter the forecast.\nAvailable 3.5L V6 Engine\r\nA robust 3.5L V6 engine is ready to deliver a thrilling drive, every drive.",
        "Details": "  <tbody>\r\n    <tr>\r\n      <td>Condition:</td>\r\n      <td>New</td>\r\n      <td>Model:</td>\r\n      <td>Camry hybrid</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Price:</td>\r\n      <td>$27.270</td>\r\n      <td>Power output:</td>\r\n      <td>118 HP (88 kW)</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Body Style:</td>\r\n      <td>Sedan</td>\r\n      <td>Doors:</td>\r\n      <td>5</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Power:</td>\r\n      <td>208 combined system net horsepower</td>\r\n      <td>Make:</td>\r\n      <td>Toyota</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Year:</td>\r\n      <td>2021</td>\r\n      <td>Electric Motor Voltage:</td>\r\n      <td>650 V (max sys.)</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Torque:</td>\r\n      <td>149 lb.-ft. (202 N·m)</td>\r\n      <td>Transmission:</td>\r\n      <td>Automatic</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Engine:</td>\r\n      <td>2.5L 4-Cyl</td>\r\n    </tr>\r\n  </tbody>\r\n",
        "Image1": "../image/product/Toyota Camry LE hybrid 2021/img1.png",
        "Image2": "../image/product/Toyota Camry LE hybrid 2021/img2.png",
        "Image3": "../image/product/Toyota Camry LE hybrid 2021/img3.png",
        "Image4": "../image/product/Toyota Camry LE hybrid 2021/img4.png",
        "Image5": "../image/product/Toyota Camry LE hybrid 2021/img5.jpg",
        "Image6": "../image/product/Toyota Camry LE hybrid 2021/img6.jpg",
        "Image7": "./image/product/Toyota Camry LE hybrid 2021/img1.png",
        "Image8": "./image/product/Toyota Camry LE hybrid 2021/img2.png"
    },
    {
        "No": "5",
        "Model": "Toyota COROLLA 2021",
        "Rangeofcar": "Sedan",
        "Brand": "Toyota",
        "Pricing": "20,025",

        "condition" : "new",
        "Description": "Sporty Front Fascia\r\nThe available honeycomb mesh grille confidently draws attention to Corolla's low, aggressive stance.\nCorolla Nightshade\r\nSleek and sharp, Corolla SE Nightshade Edition is designed to match your sense of style.\nCorolla Apex\r\nPerformance-driven handling meets statement-making style with the new 2021 Corolla Apex.",
        "Details": "<tbody>\r\n    <tr>\r\n      <td>Condition:</td>\r\n      <td>New</td>\r\n      <td>Model:</td>\r\n      <td>COROLLA</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Price:</td>\r\n      <td>$20.025</td>\r\n      <td>Fuel:</td>\r\n      <td>Unleaded</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Body Style:</td>\r\n      <td>Sedan</td>\r\n      <td>Doors:</td>\r\n      <td>5</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Power:</td>\r\n      <td>139hp</td>\r\n      <td>Make:</td>\r\n      <td>Toyota</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Year:</td>\r\n      <td>2021</td>\r\n      <td>Valves per cylinder:</td>\r\n      <td>4</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Torque:</td>\r\n      <td>126 ft lbs</td>\r\n      <td>Transmission:</td>\r\n      <td>Automatic</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Engine:</td>\r\n      <td>1.8L inline 4-cylinder</td>\r\n    </tr>\r\n  </tbody>\r\n",
        "Image1": "../image/product/Toyota COROLLA 2021/img2.png",
        "Image2": "../image/product/Toyota COROLLA 2021/img3.png",
        "Image3": "../image/product/Toyota COROLLA 2021/img4.png",
        "Image4": "../image/product/Toyota COROLLA 2021/img5.jpg",
        "Image5": "../image/product/Toyota COROLLA 2021/img6.jpg",
        "Image6": "../image/product/Toyota COROLLA 2021/img7.jpg",
        "Image7": "./image/product/Toyota COROLLA 2021/img2.png",
        "Image8": "./image/product/Toyota COROLLA 2021/img3.png"
    },
    {
        "No": "6",
        "Model": "Toyota C-HR 2021",
        "Rangeofcar": "SUV",
        "Brand": "Toyota",
        "Pricing": "21,595",
        "seller" : "best",
        "condition" : "new",
        "Description": "Distinct Design\r\nWith its striking front end and modern color palette, C-HR looks sharper than ever.\nApple CarPlay\r\nStandard Apple CarPlay 95 compatibility works with your iPhone® 86 to help you stay focused on your drive.",
        "Details": " <tbody>\r\n    <tr>\r\n      <td>Condition:</td>\r\n      <td>New</td>\r\n      <td>Model:</td>\r\n      <td>C-HR</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Price:</td>\r\n      <td>$21.595</td>\r\n      <td>Fuel:</td>\r\n      <td>Unleaded</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Body Style:</td>\r\n      <td>SUV</td>\r\n      <td>Doors:</td>\r\n      <td>5</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Power:</td>\r\n      <td>144hp</td>\r\n      <td>Make:</td>\r\n      <td>Toyota</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Year:</td>\r\n      <td>2021</td>\r\n      <td>Valves per cylinder:</td>\r\n      <td>4</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Torque:</td>\r\n      <td>139 ft lbs</td>\r\n      <td>Transmission:</td>\r\n      <td>Automatic</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Engine:</td>\r\n      <td>2.0L inline 4-cylinder</td>\r\n    </tr>\r\n  </tbody>\r\n",
        "Image1": "../image/product/Toyota C-HR 2021/img1.jpg",
        "Image2": "../image/product/Toyota C-HR 2021/img2.jpg",
        "Image3": "../image/product/Toyota C-HR 2021/img3.jpg",
        "Image4": "../image/product/Toyota C-HR 2021/img4.png",
        "Image5": "../image/product/Toyota C-HR 2021/img5.png",
        "Image6": "../image/product/Toyota C-HR 2021/img6.png",
        "Image7": "./image/product/Toyota C-HR 2021/img1.jpg",
        "Image8": "./image/product/Toyota C-HR 2021/img2.jpg"
    },
    {
        "No": "7",
        "Model": "Toyota VENZA 2021",
        "Rangeofcar": "SUV",
        "Brand": "Toyota",
        "Pricing": "32,570",
        "condition" : "new",
        "Description": "Available Digital Rearview Mirror With HomeLink®\r\nGet a clearer, wider and obstruction-free view of what's behind you.\nAvailable 12.3-In. Touchscreen Display\r\nCustomize Venza's touchscreen to easily access all your music, maps and apps\nAvailable 7-In. Multi-Information Display\r\nView essential driving information, like the Hybrid System Indicator, right before your eyes.",
        "Details": " <tbody>\r\n    <tr>\r\n      <td>Condition:</td>\r\n      <td>New</td>\r\n      <td>Model:</td>\r\n      <td>VENZA</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Price:</td>\r\n      <td>$32.570</td>\r\n      <td>Fuel:</td>\r\n      <td>Unleaded</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Body Style:</td>\r\n      <td>SUV</td>\r\n      <td>Doors:</td>\r\n      <td>5</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Power:</td>\r\n      <td>219 hp</td>\r\n      <td>Make:</td>\r\n      <td>Toyota</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Year:</td>\r\n      <td>2021</td>\r\n      <td>Valves per cylinder:</td>\r\n      <td>4</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Compression ratio:</td>\r\n      <td>14.0</td>\r\n      <td>Transmission:</td>\r\n      <td>Automatic</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Engine:</td>\r\n      <td>2.5L inline 4-cylinder</td>\r\n    </tr>\r\n  </tbody>\r\n",
        "Image1": "../image/product/Toyota VENZA 2021/img1.jpg",
        "Image2": "../image/product/Toyota VENZA 2021/img2.jpg",
        "Image3": "../image/product/Toyota VENZA 2021/img3.png",
        "Image4": "../image/product/Toyota VENZA 2021/img4.png",
        "Image5": "../image/product/Toyota VENZA 2021/img5.png",
        "Image6": "../image/product/Toyota VENZA 2021/img6.png",
        "Image7": "./image/product/Toyota VENZA 2021/img1.jpg",
        "Image8": "./image/product/Toyota VENZA 2021/img2.jpg"
    },
    {
        "No": "8",
        "Model": "KIA 2021 Rio 5-Door",
        "Rangeofcar": "Hatchback",
        "Brand": "KIA",
        "Pricing": "16,990",
        "seller" : "best",
        "condition" : "new",
        "Description": "Hatchback Utility\nRio 5-Door features a wide hatch opening and low lift-over height for easier loading and unloading.\nStrong Silhouette\r\nA refreshed design with a sleek, dynamic profile flaunts the Rio 5-Door’s athletic silhouette, standing stylishly on optional 15-inch alloy wheels.\nRear Design\r\nFeaturing a large rear window and distinctive taillight design, the Rio 5-Door is a hatchback that looks good from all angles.",
        "Details": "<tbody>\r\n    <tr>\r\n      <td>Condition:</td>\r\n      <td>New</td>\r\n      <td>Model:</td>\r\n      <td>Rio 5-Door</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Price:</td>\r\n      <td>$16.990</td>\r\n      <td>Fuel:</td>\r\n      <td>Regular Unleaded</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Body Style:</td>\r\n      <td>Hatchback</td>\r\n      <td>Doors:</td>\r\n      <td>5</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Power:</td>\r\n      <td>120 hp @ 6.300 rpm</td>\r\n      <td>Make:</td>\r\n      <td>KIA</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Year:</td>\r\n      <td>2021</td>\r\n      <td>Torque:</td>\r\n      <td>112 lb.-ft. @ 4.500 rpm</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Layout:</td>\r\n      <td>Front-Wheel Drive (FWD)</td>\r\n      <td>Transmission:</td>\r\n      <td>Automatic</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Engine:</td>\r\n      <td>1.6 liter  I-4</td>\r\n    </tr>\r\n  </tbody>\r\n",
        "Image1": "../image/product/KIA 2021 Rio 5-Door/img1.webp",
        "Image2": "../image/product/KIA 2021 Rio 5-Door/img2.webp",
        "Image3": "../image/product/KIA 2021 Rio 5-Door/img3.webp",
        "Image4": "../image/product/KIA 2021 Rio 5-Door/img4.webp",
        "Image5": "../image/product/KIA 2021 Rio 5-Door/img5.jpg",
        "Image6": "../image/product/KIA 2021 Rio 5-Door/img6.webp",
        "Image7": "./image/product/KIA 2021 Rio 5-Door/img1.webp",
        "Image8": "./image/product/KIA 2021 Rio 5-Door/img2.webp"
    },
    {
        "No": "9",
        "Model": "KIA 2021 K5",
        "Rangeofcar": "Sedan",
        "Brand": "KIA",
        "Pricing": "23,590",
        "condition" : "new",
        "Description": "Turbocharging the Test Track\r\nThe K5 GT proved itself as a true driver’s car, establishing faster acceleration and better overall handling performance than the BMW 330i in independent tests certified by AMCI Testing.\nCornering Performance\r\nThe BMW 330i couldn’t match the K5 GT’s cornering performance under both wet and dry conditions, with the K5’s all-new chassis and Pirelli P-Zero tires helping to provide better overall handling performance.",
        "Details": " <tbody>\n    <tr>\n      <td>Condition:</td>\n      <td>New</td>\n      <td>Model:</td>\n      <td>K5</td>\n    </tr>\n    <tr>\n      <td>Price:</td>\n      <td>$23.590</td>\n      <td>Fuel:</td>\n      <td>Unleaded</td>\n    </tr>\n    <tr>\n      <td>Body Style:</td>\n      <td>Sedan</td>\n      <td>Doors:</td>\n      <td>5</td>\n    </tr>\n    <tr>\n      <td>Horsepower @ RPM:</td>\n      <td>180@5500</td>\n      <td>Make:</td>\n      <td>KIA</td>\n    </tr>\n    <tr>\n      <td>Year:</td>\n      <td>2021</td>\n      <td>Torque:</td>\n      <td>195@1500</td>\n    </tr>\n    <tr>\n      <td>Number of Cylinders:</td>\n      <td>4</td>\n      <td>Transmission:</td>\n      <td>Automatic</td>\n    </tr>\n    <tr>\n      <td>Engine:</td>\n      <td>1.6 liter  I-4</td>\n    </tr>\n  </tbody>\n",
        "Image1": "../image/product/KIA 2021 K5/img1.jpg",
        "Image2": "../image/product/KIA 2021 K5/img2.jpg",
        "Image3": "../image/product/KIA 2021 K5/img3.jpg",
        "Image4": "../image/product/KIA 2021 K5/img4.jpg",
        "Image5": "../image/product/KIA 2021 K5/img5.jpg",
        "Image6": "../image/product/KIA 2021 K5/img6.jpg",
        "Image7": "./image/product/KIA 2021 K5/img1.jpg",
        "Image8": "./image/product/KIA 2021 K5/img2.jpg"
    },
    {
        "No": "10",
        "Model": "KIA 2021 Sorento Hybrid",
        "Rangeofcar": "Hybrid",
        "Brand": "KIA",
        "Pricing": "33,590",
        "status" : "hot",
        "condition" : "new",
        "Description": "Real Driving Feel\r\nUnlike other “gearless” hybrids, Sorento Hybrid shifts by wire through a full gearbox, so it still feels like driving. Thrilling driving at that.\nThrilling Acceleration\r\nHit the pedal and feel the instant torque of the combination electric motor and turbocharged engine—launching you forward into your next new experience.\nExtended Road Trip Range\r\nAdventures last longer with Sorento Hybrid's range of up to 655 miles. So drop a pin on the map, pack up, and revel in the thrill of discovery.",
        "Details": "  <tbody>\n    <tr>\n      <td>Condition:</td>\n      <td>New</td>\n      <td>Model:</td>\n      <td>Sorento</td>\n    </tr>\n    <tr>\n      <td>Price:</td>\n      <td>$33.590</td>\n      <td>Fuel:</td>\n      <td>Unleaded</td>\n    </tr>\n    <tr>\n      <td>Body Style:</td>\n      <td>Hybrid</td>\n      <td>Doors:</td>\n      <td>5</td>\n    </tr>\n    <tr>\n      <td>Horsepower @ RPM:</td>\n      <td>227@Not Listed</td>\n      <td>Make:</td>\n      <td>KIA</td>\n    </tr>\n    <tr>\n      <td>Year:</td>\n      <td>2021</td>\n      <td>Torque:</td>\n      <td>258@Not Listed</td>\n    </tr>\n    <tr>\n      <td>Number of Cylinders:</td>\n      <td>4</td>\n      <td>Transmission:</td>\n      <td>Automatic</td>\n    </tr>\n    <tr>\n      <td>Engine:</td>\n      <td>1.6 liter  I-4</td>\n    </tr>\n  </tbody>\n",
        "Image1": "../image/product/KIA 2021 Sorento Hybrid/img1.jpg",
        "Image2": "../image/product/KIA 2021 Sorento Hybrid/img2.jpg",
        "Image3": "../image/product/KIA 2021 Sorento Hybrid/img3.jpg",
        "Image4": "../image/product/KIA 2021 Sorento Hybrid/img4.jpg",
        "Image5": "../image/product/KIA 2021 Sorento Hybrid/img5.jpg",
        "Image6": "../image/product/KIA 2021 Sorento Hybrid/img6.jpg",
        "Image7": "./image/product/KIA 2021 Sorento Hybrid/img1.jpg",
        "Image8": "./image/product/KIA 2021 Sorento Hybrid/img2.jpg"
    },
    {
        "No": "11",
        "Model": "KIA 2021 Telluride",
        "Rangeofcar": "SUV",
        "Brand": "KIA",
        "Pricing": "32,190",
        "condition" : "new",
        "Description": "Driver’s Cockpit\nTake command with an available 10.25” touchscreen display1and features that let you amplify your voice to rear passengers or use only the front row speakers.\nCaptain’s Seats\nAvailable reclining dual captain’s chairs2 slide forward at the touch of a button for 3rd row access. Rear passengers can enjoy available dual sunroofs and standard USB ports.",
        "Details": "  <tbody>\r\n    <tr>\r\n      <td>Condition:</td>\r\n      <td>New</td>\r\n      <td>Model:</td>\r\n      <td>Telluride</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Price:</td>\r\n      <td>$32.190</td>\r\n      <td>Fuel:</td>\r\n      <td>Unleaded</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Body Style:</td>\r\n      <td>SUV</td>\r\n      <td>Doors:</td>\r\n      <td>5</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Horsepower @ RPM:</td>\r\n      <td>291@6000</td>\r\n      <td>Make:</td>\r\n      <td>KIA</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Year:</td>\r\n      <td>2021</td>\r\n      <td>Torque:</td>\r\n      <td>262@5200</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Number of Cylinders:</td>\r\n      <td>6</td>\r\n      <td>Transmission:</td>\r\n      <td>Automatic</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Engine:</td>\r\n      <td>3.8L V6</td>\r\n    </tr>\r\n  </tbody>\r\n",
        "Image1": "../image/product/KIA 2021 Telluride/img1.jpg",
        "Image2": "../image/product/KIA 2021 Telluride/img2.jpg",
        "Image3": "../image/product/KIA 2021 Telluride/img3.jpg",
        "Image4": "../image/product/KIA 2021 Telluride/img4.jpg",
        "Image5": "../image/product/KIA 2021 Telluride/img5.jpg",
        "Image6": "../image/product/KIA 2021 Telluride/img6.jpg",
        "Image7": "../image/product/KIA 2021 Telluride/img1.jpg",
        "Image8": "../image/product/KIA 2021 Telluride/img2.jpg"
    },
    {
        "No": "12",
        "Model": "HYUNDAI IONIQ Hybrid",
        "Rangeofcar": "Hatchback",
        "Brand": "HYUNDAI",
        "Pricing": "23,400",
        "condition" : "new",
        "Description": "More style per gallon.\r\nThe hybrid efficiency is evident in its bold, airflow-inspired form and lines. And its look has been highlighted with a mesh pattern grille, striking LED lights and Eco-spoke wheels.\nModern space. The most in its class.\r\nInside there’s room. Lots of it. Stretch out in this stylish space that thoughtfully uses bio-fabrics, recycled plastics and other eco-friendly materials. Plus, you’ll find the perfect touch of modern features like an available 10.25-inch touchscreen.",
        "Details": "<tbody>\r\n    <tr>\r\n      <td>Condition:</td>\r\n      <td>New</td>\r\n      <td>Model:</td>\r\n      <td>IONIQ</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Price:</td>\r\n      <td>$23.400</td>\r\n      <td>Battery system capacity:</td>\r\n      <td>1.56 kWh</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Body Style:</td>\r\n      <td>Hatchback</td>\r\n      <td>Doors:</td>\r\n      <td>5</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Horsepower @ RPM:</td>\r\n      <td>104 @ 5700</td>\r\n      <td>Make:</td>\r\n      <td>Hyundai</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Year:</td>\r\n      <td>2021</td>\r\n      <td>Torque:</td>\r\n      <td>109 @ 4000</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Power output:</td>\r\n      <td>32 kW (43 hp)</td>\r\n      <td>Transmission:</td>\r\n      <td>Automatic</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Engine:</td>\r\n      <td>1.6L GDI DOHC 16-valve inline 4-cylinder</td>\r\n    </tr>\r\n  </tbody>\r\n",
        "Image1": "../image/product/HYUNDAI IONIQ Hybrid/img1.jpg",
        "Image2": "../image/product/HYUNDAI IONIQ Hybrid/img2.jpg",
        "Image3": "../image/product/HYUNDAI IONIQ Hybrid/img3.jpg",
        "Image4": "../image/product/HYUNDAI IONIQ Hybrid/img4.jpg",
        "Image5": "../image/product/HYUNDAI IONIQ Hybrid/img5.jpg",
        "Image6": "../image/product/HYUNDAI IONIQ Hybrid/img6.jpg",
        "Image7": "./image/product/HYUNDAI IONIQ Hybrid/img1.jpg",
        "Image8": "./image/product/HYUNDAI IONIQ Hybrid/img2.jpg"
    },
    {
        "No": "13",
        "Model": "HYUNDAI VELOSTER",
        "Rangeofcar": "Hatchback",
        "Brand": "HYUNDAI",
        "Pricing": "18,900",
        "condition" : "new",
        "Description": "Every side is its bold side.⁠\r\nFun to look at. Fun to drive. 2021 Veloster continues to be a unique expression of Hyundai’s audacious side, with a build quality that’s as solid as its community of die-hard owners.\nCorner the market on corners.\r\nThe Veloster doesn’t just look different, it feels different—especially when you’re ripping it around hairpin turns and tight corners.",
        "Details": " <tbody>\n    <tr>\n      <td>Condition:</td>\n      <td>New</td>\n      <td>Model:</td>\n      <td>VELOSTER</td>\n    </tr>\n    <tr>\n      <td>Price:</td>\n      <td>$18.900</td>\n      <td>Fuel system:</td>\n      <td>Gasoline Direct Injection (GDI)</td>\n    </tr>\n    <tr>\n      <td>Body Style:</td>\n      <td>Hatchback</td>\n      <td>Doors:</td>\n      <td>5</td>\n    </tr>\n    <tr>\n      <td>Horsepower @ RPM:</td>\n      <td>147 @ 6200</td>\n      <td>Make:</td>\n      <td>Hyundai</td>\n    </tr>\n    <tr>\n      <td>Year:</td>\n      <td>2021</td>\n      <td>Torque:</td>\n      <td>132 @ 4500</td>\n    </tr>\n    <tr>\n      <td>Displacement (liters):</td>\n      <td>2.0</td>\n      <td>Transmission:</td>\n      <td>Automatic</td>\n    </tr>\n    <tr>\n      <td>Engine:</td>\n      <td>Inline 4-cylinder</td>\n    </tr>\n  </tbody>\n",
        "Image1": "../image/product/HYUNDAI VELOSTER/img1.jpg",
        "Image2": "../image/product/HYUNDAI VELOSTER/img2.jpg",
        "Image3": "../image/product/HYUNDAI VELOSTER/img3.jpg",
        "Image4": "../image/product/HYUNDAI VELOSTER/img4.jpg",
        "Image5": "../image/product/HYUNDAI VELOSTER/img5.jpg",
        "Image6": "../image/product/HYUNDAI VELOSTER/img6.jpg"
    },
    {
        "No": "14",
        "Model": "HYUNDAI VELOSTER N",
        "Rangeofcar": "Hatchback",
        "Brand": "HYUNDAI",
        "Pricing": "32,250",
        "condition" : "new",
        "Description": "The roads are public. But you’ll own the corners.\r\nThe nimble chassis was built with the philosophy that there’s nothing more satisfying than devouring the toughest hairpin turns and snaking roads our national highway system has to offer.\nSeamless shifts. Quick power.\r\nWhen it comes to making fast, smooth and efficient shifts, you have two performance enhancing choices. A standard 6-speed close-ratio manual or the available quick-shifting N 8-speed Wet Dual Clutch Transmission with paddle shifters.",
        "Details": "  <tbody>\r\n    <tr>\r\n      <td>Condition:</td>\r\n      <td>New</td>\r\n      <td>Model:</td>\r\n      <td>VELOSTER</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Price:</td>\r\n      <td>$32.250</td>\r\n      <td>Fuel system:</td>\r\n      <td>Gasoline Direct Injection (GDI)</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Body Style:</td>\r\n      <td>Hatchback</td>\r\n      <td>Doors:</td>\r\n      <td>5</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Horsepower @ RPM:</td>\r\n      <td>275 hp @ 6000</td>\r\n      <td>Make:</td>\r\n      <td>Hyundai</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Year:</td>\r\n      <td>2021</td>\r\n      <td>Torque:</td>\r\n      <td>260 @ 1450</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Displacement (liters):</td>\r\n      <td>2.0</td>\r\n      <td>Transmission:</td>\r\n      <td>Automatic</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Engine:</td>\r\n      <td>Inline 4-cylinder Turbo</td>\r\n    </tr>\r\n  </tbody>\r\n",
        "Image1": "../image/product/HYUNDAI VELOSTER N/img1.png",
        "Image2": "../image/product/HYUNDAI VELOSTER N/img2.png",
        "Image3": "../image/product/HYUNDAI VELOSTER N/img3.png",
        "Image4": "../image/product/HYUNDAI VELOSTER N/img4.png",
        "Image5": "../image/product/HYUNDAI VELOSTER N/img5.png",
        "Image6": "../image/product/HYUNDAI VELOSTER N/img6.png"
    },
    {
        "No": "15",
        "Model": "HYUNDAI VENUE",
        "Rangeofcar": "SUV",
        "Brand": "HYUNDAI",
        "Pricing": "18,750",
        "status" : "hot",
        "condition" : "new",
        "Description": "Start it up.⁠\r\nThis is where it all happens. A forward-thinking SUV for a fast-paced life, Venue was made to conquer the city. Small, nimble and safe, Venue is a powerhouse that gets the job done, with features and advanced technology that look out for you, to keep you moving, connected, and best of all, safe.",
        "Details": "  <tbody>\r\n    <tr>\r\n      <td>Condition:</td>\r\n      <td>New</td>\r\n      <td>Model:</td>\r\n      <td>VENUE</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Price:</td>\r\n      <td>$18.750</td>\r\n      <td>Valve train:</td>\r\n      <td>Continuously Variable Valve Timing (CVVT)</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Body Style:</td>\r\n      <td>SUV</td>\r\n      <td>Doors:</td>\r\n      <td>5</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Horsepower @ RPM:</td>\r\n      <td>121 @ 6300 RPM</td>\r\n      <td>Make:</td>\r\n      <td>Hyundai</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Year:</td>\r\n      <td>2021</td>\r\n      <td>Torque:</td>\r\n      <td>113 @ 4500</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Displacement (liters):</td>\r\n      <td>2.0</td>\r\n      <td>Transmission:</td>\r\n      <td>Automatic</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Engine:</td>\r\n      <td>Smartstream 4-cylinder</td>\r\n    </tr>\r\n  </tbody>\r\n",
        "Image1": "../image/product/HYUNDAI VENUE/img1.jpg",
        "Image2": "../image/product/HYUNDAI VENUE/img2.jpg",
        "Image3": "../image/product/HYUNDAI VENUE/img3.jpg",
        "Image4": "../image/product/HYUNDAI VENUE/img4.jpg",
        "Image5": "../image/product/HYUNDAI VENUE/img5.jpg",
        "Image6": "../image/product/HYUNDAI VENUE/img6.jpg",
        "Image7": "./image/product/HYUNDAI VENUE/img1.jpg",
        "Image8": "./image/product/HYUNDAI VENUE/img2.jpg"
    },
    {
        "No": "16",
        "Model": "Jeep Renegade Latitude",
        "Rangeofcar": "PreOwned Cars",
        "Brand": "JEEP",
        "Pricing": "20,000",
        "condition" : "own",
        "Description": "Jeep Certified Pre-Owned Vehicle Program\nJeep Certified Pre-Owned vehicles must pass a history check and rigorous 125-point mechanical and appearance inspection and must be 5 model years old or newer and have less than 75,000 miles.",
        "Details": "<tbody>\r\n    <tr>\r\n      <td>Condition:</td>\r\n      <td>PreOwned</td>\r\n      <td>Model:</td>\r\n      <td>Renegade Latitude</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Price:</td>\r\n      <td>$20.000</td>\r\n      <td>MPG:</td>\r\n      <td>24 City / 31 Hwy</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Body Style:</td>\r\n      <td>SUV</td>\r\n      <td>Seats:</td>\r\n      <td>5 Seats</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Power:</td>\r\n      <td>180 Horsepower</td>\r\n      <td>Make:</td>\r\n      <td>JEEP</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Year:</td>\r\n      <td>2017</td>\r\n      <td>Mileage:</td>\r\n      <td>10,488 Miles</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Drivetrain:</td>\r\n      <td>Four Wheel Drive</td>\r\n      <td>Transmission:</td>\r\n      <td>Automatic</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Engine:</td>\r\n      <td>2.4L 4cyl 9A</td>\r\n    </tr>\r\n  </tbody>\r\n",
        "Image1": "../image/product/Jeep Renegade Latitude/img1.jpg",
        "Image2": "../image/product/Jeep Renegade Latitude/img2.jpg",
        "Image3": "../image/product/Jeep Renegade Latitude/img3.jpg",
        "Image4": "../image/product/Jeep Renegade Latitude/img4.jpg",
        "Image5": "../image/product/Jeep Renegade Latitude/img5.jpg",
        "Image6": "../image/product/Jeep Renegade Latitude/img6.jpg"
    },
    {
        "No": "17",
        "Model": "Jeep Renegade Sport",
        "Rangeofcar": "PreOwned Cars",
        "Brand": "JEEP",
        "Pricing": "21,000",
        "condition" : "own",
        "Description": "Jeep Certified Pre-Owned Vehicle Program\nJeep Certified Pre-Owned vehicles must pass a history check and rigorous 125-point mechanical and appearance inspection and must be 5 model years old or newer and have less than 75.000 miles.",
        "Details": "  <tbody>\r\n    <tr>\r\n      <td>Condition:</td>\r\n      <td>PreOwned</td>\r\n      <td>Model:</td>\r\n      <td>Renegade Sport</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Price:</td>\r\n      <td>$21.000</td>\r\n      <td>MPG:</td>\r\n      <td>21 City / 29 Hwy</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Body Style:</td>\r\n      <td>SUV</td>\r\n      <td>Seats:</td>\r\n      <td>5 Seats</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Power:</td>\r\n      <td>180 Horsepower</td>\r\n      <td>Make:</td>\r\n      <td>JEEP</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Year:</td>\r\n      <td>2020</td>\r\n      <td>Mileage:</td>\r\n      <td>12,505 Miles</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Drivetrain:</td>\r\n      <td>Four Wheel Drive</td>\r\n      <td>Transmission:</td>\r\n      <td>Automatic</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Engine:</td>\r\n      <td>2.4L 4cyl 9A</td>\r\n    </tr>\r\n  </tbody>\r\n",
        "Image1": "../image/product/Jeep Renegade Sport/img1.jpg",
        "Image2": "../image/product/Jeep Renegade Sport/img2.jpg",
        "Image3": "../image/product/Jeep Renegade Sport/img3.jpg",
        "Image4": "../image/product/Jeep Renegade Sport/img4.jpg",
        "Image5": "../image/product/Jeep Renegade Sport/img5.jpg",
        "Image6": "../image/product/Jeep Renegade Sport/img6.jpg"
    },
    {
        "No": "18",
        "Model": "Jeep Cherokee Trailhawk",
        "Rangeofcar": "PreOwned Cars",
        "Brand": "JEEP",
        "Pricing": "30,000",
        "condition" : "own",
        "Description": "Jeep Certified Pre-Owned Vehicle Program\nJeep Certified Pre-Owned vehicles must pass a history check and rigorous 125-point mechanical and appearance inspection and must be 5 model years old or newer and have less than 75.000 miles.",
        "Details": "  <tbody>\r\n    <tr>\r\n      <td>Condition:</td>\r\n      <td>PreOwned</td>\r\n      <td>Model:</td>\r\n      <td>Cherokee Trailhawk</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Price:</td>\r\n      <td>$30.000</td>\r\n      <td>MPG:</td>\r\n      <td>18 City / 24 Hwy</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Body Style:</td>\r\n      <td>SUV</td>\r\n      <td>Seats:</td>\r\n      <td>5 Seats</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Power:</td>\r\n      <td>270 Horsepower</td>\r\n      <td>Make:</td>\r\n      <td>JEEP</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Year:</td>\r\n      <td>2020</td>\r\n      <td>Mileage:</td>\r\n      <td>8,723 Miles</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Drivetrain:</td>\r\n      <td>Four Wheel Drive</td>\r\n      <td>Transmission:</td>\r\n      <td>Automatic</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Engine:</td>\r\n      <td>2.4L 4cyl Turbo 9A</td>\r\n    </tr>\r\n  </tbody>\r\n",
        "Image1": "../image/product/Jeep Cherokee Trailhawk/img1.jpg",
        "Image2": "../image/product/Jeep Cherokee Trailhawk/img2.jpg",
        "Image3": "../image/product/Jeep Cherokee Trailhawk/img3.jpg",
        "Image4": "../image/product/Jeep Cherokee Trailhawk/img4.jpg",
        "Image5": "../image/product/Jeep Cherokee Trailhawk/img5.jpg",
        "Image6": "../image/product/Jeep Cherokee Trailhawk/img6.jpg"
    },
    {
        "No": "19",
        "Model": "Jeep Cherokee\nLimited",
        "Rangeofcar": "PreOwned Cars",
        "Brand": "JEEP",
        "Pricing": "30,500",
        "condition" : "own",
        "Description": "Jeep Certified Pre-Owned Vehicle Program\nJeep Certified Pre-Owned vehicles must pass a history check and rigorous 125-point mechanical and appearance inspection and must be 5 model years old or newer and have less than 75.000 miles.",
        "Details": "    <tr>\r\n      <td>Condition:</td>\r\n      <td>PreOwned</td>\r\n      <td>Model:</td>\r\n      <td>Cherokee Limited</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Price:</td>\r\n      <td>$30.500</td>\r\n      <td>MPG:</td>\r\n      <td>19 City / 27 Hwy</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Body Style:</td>\r\n      <td>SUV</td>\r\n      <td>Seats:</td>\r\n      <td>5 Seats</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Power:</td>\r\n      <td>271 Horsepower</td>\r\n      <td>Make:</td>\r\n      <td>JEEP</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Year:</td>\r\n      <td>2020</td>\r\n      <td>Mileage:</td>\r\n      <td>2,055 Miles</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Drivetrain:</td>\r\n      <td>Four Wheel Drive</td>\r\n      <td>Transmission:</td>\r\n      <td>Automatic</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Engine:</td>\r\n      <td>3.2L 6cyl 9A</td>\r\n    </tr>\r\n  </tbody>\r\n",
        "Image1": "../image/product/Jeep Cherokee Limited/img1.jpg",
        "Image2": "../image/product/Jeep Cherokee Limited/img2.jpg",
        "Image3": "../image/product/Jeep Cherokee Limited/img3.jpg",
        "Image4": "../image/product/Jeep Cherokee Limited/img4.jpg",
        "Image5": "../image/product/Jeep Cherokee Limited/img5.jpg",
        "Image6": "../image/product/Jeep Cherokee Limited/img6.jpg"
    }
];